/**
 * Runtime stub generated by Compact compiler for allowlist.compact
 */
'use strict';

exports.contract = {
  circuits: {
    addMember: function(commitment) { return []; },
    proveMembership: function() { return []; },
    getMemberCount: function() { return 0n; },
    getVerifiedCount: function() { return 0n; }
  }
};
