/**
 * Type declarations generated by Compact compiler for allowlist.compact
 */

import type { WitnessContext } from '@midnight-ntwrk/compact-runtime';

export type Bytes32 = Uint8Array;
export type Field = bigint;

export interface LedgerState {
  allowlistRoot: Bytes32;
  memberCount: bigint;
  verifiedCount: bigint;
  usedNullifiers: Map<Field, boolean>;
  allowlistName: string;
}

export interface Witnesses<T = unknown> {
  memberSecret: (context: WitnessContext<LedgerState, T>) => [T, Bytes32];
}

export interface Contract<T = unknown> {
  witnesses: Witnesses<T>;
  circuits: {
    addMember(commitment: Bytes32): void;
    proveMembership(): void;
    getMemberCount(): bigint;
    getVerifiedCount(): bigint;
  };
}

export declare const contract: Contract;
export default contract;
